theme: jekyll-theme-minimal
title: Joemari's website
locale: en_US
owner: Joemari Pulido
  bio: This is a website to showcase Joemari Pulido's involvement in research. Currently, Joemari is a research assistant and lab manager at the Human Psychophysiology Lab at Providence College led by Dr. Joanna Morris. 
  email: jpulido@friars.providence.edu
  linkedin: Joemari Javier Pulido 
 
